### ISSUE TITLE
Should the project be discontinued?

### ISSUE THREAD

**Issue by visuve** [markusl/GoogleTestRunner#20]
Hi,

It seems that [GoogleTestAdapter](https://github.com/csoltenborn/GoogleTestAdapter) is succeeding because our development is dead.

Neither me, @markusl or @vkantchev  seem to have time to look through the pull requests and merge them. 

Should we discontinue the project and encourage the users to migrate to GoogleTestAdapter?

**Comment by vkantchev** [comment]
@Huemac I agree. GoogleTestAdapter is much better supported, and probably will be in the future, because it is a C# rewrite.

**Comment by markusl** [comment]
Since I have currently very limited time to maintain this extension, I suggest you use GoogleTestAdapter instead as it seems to be port of this extension written in C# and more actively maintained :)

Best Regards,
Markus
