### ISSUE TITLE
Does not work with Visual Studio 2015 Update 3

### ISSUE THREAD

**Issue by frast** [markusl/GoogleTestRunner#22]
I get the following error message after the tests ran:

Die Datei oder Assembly "FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
   bei FSharp.Data.Runtime.XmlRuntime.GetChildrenArray(XmlElement value, String nameWithNS)
   bei FSharp.Data.Runtime.XmlRuntime.ConvertArray[R](XmlElement xml, String nameWithNS, Func`2 f)
   bei GoogleTestRunner.ResultParser.getResults(IMessageLogger logger, String outputPath, FSharpList`1 testCases)
   bei GoogleTestRunner.GoogleTestExecutor.runOnce(IFrameworkHandle framework, IRunContext runContext, FSharpList`1 allCases, FSharpList`1 cases, String executable, Boolean runAll)
   bei GoogleTestRunner.GoogleTestExecutor.runTests(FSharpList`1 allCases, IEnumerable`1 cases, IRunContext runContext, IFrameworkHandle framework, Boolean runAll)

**Comment by davidkvc** [comment]
Same for me, not tests run even though I can see 2 tests in Test Explorer

------ Run test started ------
Found 2 tests, resolving symbols
Loading symbols from C:\Users\user\Documents\Visual Studio 2015\Projects\CPPProj\Debug\CPPProj_tests.exe
From C:\Users\user\Documents\Visual Studio 2015\Projects\CPPProj\Debug\CPPProj_tests.exe, found 2 symbols in 19 ms
In C:\Users\user\Documents\Visual Studio 2015\Projects\CPPProj\Debug, running: C:\Users\user\Documents\Visual Studio 2015\Projects\CPPProj\Debug\CPPProj_tests.exe  --gtest_output="xml:C:\Users\user\AppData\Local\Temp\tmp60DB.tmp" 
Opened results from C:\Users\user\AppData\Local\Temp\tmp60DB.tmp
Could not load file or assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at FSharp.Data.Runtime.XmlRuntime.GetChildrenArray(XmlElement value, String nameWithNS)
   at FSharp.Data.Runtime.XmlRuntime.ConvertArray[R](XmlElement xml, String nameWithNS, Func`2 f)
   at GoogleTestRunner.ResultParser.getResults(IMessageLogger logger, String outputPath, FSharpList`1 testCases)
   at GoogleTestRunner.GoogleTestExecutor.runOnce(IFrameworkHandle framework, IRunContext runContext, FSharpList`1 allCases, FSharpList`1 cases, String executable, Boolean runAll)
   at GoogleTestRunner.GoogleTestExecutor.runTests(FSharpList`1 allCases, IEnumerable`1 cases, IRunContext runContext, IFrameworkHandle framework, Boolean runAll)
No test is available in C:\Users\user\Documents\Visual Studio 2015\Projects\CPPProj\Debug\CPPProj_tests.exe. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
========== Run test finished: 0 run (0:00:00,3496363) ==========

**Comment by visuve** [comment]
Related: https://github.com/markusl/GoogleTestRunner/issues/21 https://github.com/markusl/GoogleTestRunner/issues/20
