### ISSUE TITLE
TestRunner does not respect Working Directory set in Debugging Properties

### ISSUE THREAD

**Issue by kiron1** [markusl/GoogleTestRunner#7]
Our test executable expects to be invoked in a specific working directory where further assets are located.

From inspecting the code of GoogleTestRunner it automatically uses the directory where the executable is located. Is it be possible to extend GoogleTestRunner to use the same path for running the test as configured in the Debugging properties of the project?

**Comment by markusl** [comment]
Hi kiron1.

Generally, test executables should be self-contained and should have no dependencies to outside system. Would it be possible to configure your build system to copy the required assets to same place it puts the executable?

Regards,
Markus

**Comment by kiron1** [comment]
Hi Markus,

Thanks for quick reply.

Unfortunately coping is not an option, since the assets are quite huge. Therefor we would like to avoid any coping. We tried to use symlinks, but this does not work in a cross platform why without requireing Administrator rights on Windows.

**Comment by sabarn01** [comment]
mklink doesn't require administrator privileges.

On Mon, Jan 19, 2015 at 5:53 AM, kiron1 <notifications@github.com> wrote:

> Hi Markus,
>
> Thanks for quick reply.
>
> Unfortunately coping is not an option, since the assets are quite huge.
> Therefor we would like to avoid any coping. We tried to use symlinks, but
> this does not work in a cross platform why without requireing Administrator
> rights on Windows.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markusl/GoogleTestRunner/issues/7#issuecomment-70475706>
> .
>



-- 
Adam Barnett

**Comment by kiron1** [comment]
Thank you sabarn01, previously the build script was using mklink /D (which requires Administrator privileges), changed it mklink /J (which does not require Administrator privileges).
